/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BL.TravelGuideBL;
import GUI.MainGUI;
/**
 *
 * @author Patrick
 */
public class CompareToolDialog extends javax.swing.JDialog {
    public String travelday;
    private MainGUI gui;
    public int sortSelect;
    public TravelGuideBL tgbl = TravelGuideBL.getTravelGuideData();

    public CompareToolDialog(java.awt.Frame parent, boolean modal, MainGUI gui) {
        super(parent, modal);
        initComponents();
        this.gui = gui;
        cbInit();
        
    }
    
/**
     * Creates new form CompareToolDialog
     */
        /**Adds the dates to the combobox
         * 
         */
        public void cbInit()
    {            
            TravelGuideBL bl = tgbl.getWeatherData(0);
            cbDay.addItem("TODAY");
            cbDay.addItem("TOMORROW");
            cbDay.addItem(bl.getList().get(bl.getNextDay()+8).getDt_txt().replace('-', '.').substring(0, 10));
            cbDay.addItem(bl.getList().get(bl.getNextDay()+16).getDt_txt().replace('-', '.').substring(0, 10));
            cbDay.addItem(bl.getList().get(bl.getNextDay()+24).getDt_txt().replace('-', '.').substring(0, 10));
            cbDay.setSelectedIndex(0);
            cbDay.updateUI();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSelectionGroup = new javax.swing.ButtonGroup();
        cbDay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        bnOk = new javax.swing.JButton();
        bnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbTemp = new javax.swing.JRadioButton();
        rbHumid = new javax.swing.JRadioButton();
        rbPress = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CompareToolDialog");
        setMinimumSize(new java.awt.Dimension(250, 120));

        getContentPane().add(cbDay, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        bnOk.setText("OK");
        bnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnOkActionPerformed(evt);
            }
        });
        jPanel2.add(bnOk);

        bnCancel.setText("Cancel");
        bnCancel.setToolTipText("");
        bnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(bnCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        btSelectionGroup.add(rbTemp);
        rbTemp.setText("Sort by Temperature");
        jPanel3.add(rbTemp);

        btSelectionGroup.add(rbHumid);
        rbHumid.setText("Sort by Humidity");
        jPanel3.add(rbHumid);

        btSelectionGroup.add(rbPress);
        rbPress.setText("Sort by Air Pressure");
        jPanel3.add(rbPress);

        btSelectionGroup.add(jRadioButton1);
        jRadioButton1.setText("No sort");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void bnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnOkActionPerformed
        String dayOfTravel = String.valueOf(cbDay.getSelectedItem());
        this.setVisible(false);
        travelday = dayOfTravel;
        if(rbTemp.isSelected())
        {
            sortSelect = 1;
        }
        else if(rbHumid.isSelected())
        {
            sortSelect = 2;
        }
        else if(rbPress.isSelected())
        {
            sortSelect = 3;
        }
        else
        {
            sortSelect = 1;
        }
        System.out.println(sortSelect);
        CompToolGUI wp = new CompToolGUI(gui, true, this);
        wp.setVisible(true);       
    }//GEN-LAST:event_bnOkActionPerformed

    private void bnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bnCancelActionPerformed

    public String getTravelday() {
        return travelday;
    }
    public int returnSort() {
        return sortSelect;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCancel;
    private javax.swing.JButton bnOk;
    private javax.swing.ButtonGroup btSelectionGroup;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton rbHumid;
    private javax.swing.JRadioButton rbPress;
    private javax.swing.JRadioButton rbTemp;
    // End of variables declaration//GEN-END:variables

    
}
