/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.TravelGuideBL;
import DAL.Day;
import java.util.ArrayList;



/**
 *
 * @author Patrick
 */
public class CompareToolDialog extends javax.swing.JDialog {

    public CompareToolDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cbInit();
        
    }
    
/**
     * Creates new form CompareToolDialog
     */
        public void cbInit()
    {            
            cbDay.addItem("TODAY");
            cbDay.addItem("TOMORROW");
            cbDay.addItem("DAY3");
            cbDay.addItem("DAY4");
            cbDay.addItem("DAY5");
            cbDay.setSelectedIndex(0);
            cbDay.updateUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbDay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbTemp = new javax.swing.JRadioButton();
        rbHumid = new javax.swing.JRadioButton();
        rbPress = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CompareToolDialog");
        setMinimumSize(new java.awt.Dimension(250, 120));

        getContentPane().add(cbDay, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout());

        jButton2.setText("OK");
        jPanel2.add(jButton2);

        jButton3.setText("Cancel");
        jButton3.setToolTipText("");
        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        buttonGroup1.add(rbTemp);
        rbTemp.setText("Sort by Temperature");
        jPanel3.add(rbTemp);

        buttonGroup1.add(rbHumid);
        rbHumid.setText("Sort by Humidity");
        jPanel3.add(rbHumid);

        buttonGroup1.add(rbPress);
        rbPress.setText("Sort by Air Pressure");
        jPanel3.add(rbPress);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompareToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompareToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompareToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompareToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CompareToolDialog dialog = new CompareToolDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbHumid;
    private javax.swing.JRadioButton rbPress;
    private javax.swing.JRadioButton rbTemp;
    // End of variables declaration//GEN-END:variables
}
