/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import BL.TravelGuideBL;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdom2.Document;

/**
 *
 * @author Patrick
 */
public class MainGUI extends javax.swing.JFrame {

    TravelGuideBL tgbl = TravelGuideBL.getTravelGuideData();
    private Document doc;
    private int selectDay;
    
    
    /** Creates new form NewJFrame */
    public MainGUI() {
        initComponents();
        this.setIconImage(new ImageIcon("src/main/java/weather.png").getImage());
        try {
            tgbl.loadData();
        } catch (Exception ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbInit();
        //Saves the location data when closing the program
        this.addWindowListener(new WindowAdapter() {
            
            public void windowClosing(WindowEvent evt) {
                
                doc = tgbl.createDocument("LocData");
                tgbl.prepareXML(doc);
                try {
                    tgbl.writeXML(doc);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Failed to save");
                }
            }
        });
    }
    
    /**Initialize the combobox
     * 
     */
    public void cbInit() {
        if(tgbl.getLocdata().size() > 0)
        {
            for (int i = 0; i < tgbl.getLocdata().size(); i++) {
                cbLocation.addItem(tgbl.getLocdata().get(i).city);
            }  
            cbLocation.setSelectedIndex(0);
            cbLocation.updateUI();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        cbLocation = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        pnFirstTwoDays = new javax.swing.JPanel();
        lbDay1 = new javax.swing.JLabel();
        lbDay2 = new javax.swing.JLabel();
        pnOtherDays = new javax.swing.JPanel();
        lbDay3 = new javax.swing.JLabel();
        lbDay4 = new javax.swing.JLabel();
        lbDay5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAdd = new javax.swing.JMenuItem();
        miRemove = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miComp = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WeatherTraveller");
        setMinimumSize(new java.awt.Dimension(500, 370));

        cbLocation.setForeground(new java.awt.Color(255, 255, 255));
        cbLocation.setMaximumRowCount(20);
        cbLocation.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocationActionPerformed(evt);
            }
        });
        getContentPane().add(cbLocation, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        pnFirstTwoDays.setBackground(new java.awt.Color(0, 153, 204));
        pnFirstTwoDays.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pnFirstTwoDays.setLayout(new java.awt.GridLayout(1, 2));

        lbDay1.setForeground(new java.awt.Color(255, 204, 0));
        lbDay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDay1MouseClicked(evt);
            }
        });
        pnFirstTwoDays.add(lbDay1);

        lbDay2.setForeground(new java.awt.Color(255, 255, 255));
        lbDay2.setText("jLabel2");
        lbDay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDay2MouseClicked(evt);
            }
        });
        pnFirstTwoDays.add(lbDay2);

        jPanel1.add(pnFirstTwoDays);

        pnOtherDays.setBackground(new java.awt.Color(0, 194, 212));
        pnOtherDays.setForeground(new java.awt.Color(255, 255, 255));
        pnOtherDays.setLayout(new java.awt.GridLayout(1, 3));

        lbDay3.setForeground(new java.awt.Color(255, 255, 255));
        lbDay3.setText("jLabel3");
        lbDay3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDay3MouseClicked(evt);
            }
        });
        pnOtherDays.add(lbDay3);

        lbDay4.setForeground(new java.awt.Color(255, 255, 255));
        lbDay4.setText("jLabel4");
        lbDay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDay4MouseClicked(evt);
            }
        });
        pnOtherDays.add(lbDay4);

        lbDay5.setForeground(new java.awt.Color(255, 255, 255));
        lbDay5.setText("jLabel5");
        lbDay5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDay5MouseClicked(evt);
            }
        });
        pnOtherDays.add(lbDay5);

        jPanel1.add(pnOtherDays);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Edit");

        miAdd.setText("Add");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddActionPerformed(evt);
            }
        });
        jMenu1.add(miAdd);

        miRemove.setText("Remove");
        miRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoveActionPerformed(evt);
            }
        });
        jMenu1.add(miRemove);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");

        miComp.setText("Compare");
        miComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompActionPerformed(evt);
            }
        });
        jMenu2.add(miComp);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Info");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoveActionPerformed
        try{
           int index = cbLocation.getSelectedIndex();
           tgbl.remove(index);
           cbLocation.removeItemAt(index);
           cbLocation.updateUI();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Nothing to remove!");
        }
        
    }//GEN-LAST:event_miRemoveActionPerformed

    private void miAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddActionPerformed
        LocationDialog ldia = new LocationDialog(this, true);
        ldia.setVisible(true);
        if (ldia.isAddOK()) {
            tgbl.addLocation(ldia.getLd());
            cbLocation.addItem(ldia.getLd().getCity());
            cbLocation.updateUI();
        }
    }//GEN-LAST:event_miAddActionPerformed
/**Set the text to the gui
 * 
 * @param evt 
 */
    private void cbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocationActionPerformed
        TravelGuideBL bl =tgbl.getWeatherData(cbLocation.getSelectedIndex());
        //System.out.println(String.valueOf(bl.getList().get(0).getWeather().get(0).getDescription()));
        try {
            //jLabel1.setText(String.valueOf("Today:"+bl.getList().get(0).getWeather().get(0).getDescription()+ " "+ (bl.getList().get(0).getMain().getTemp() - 273.15)+" "));
            lbDay1.setText("<html><body><h2>TODAY</h2><p style='font-size:130%;'>"
                    +String.valueOf(bl.getList().get(0).getMain().getTemp()-273.15).substring(0, 3)+" °C </p>"
                    +bl.getList().get(0).getWeather().get(0).getDescription()+"<br>Min/Max: "
                    +String.valueOf(bl.avgminTemp(0)).substring(0, 3)+"° / "
                    + String.valueOf(bl.avgmaxTemp(0)).substring(0, 3)
                    +"°<br>Humidity: "+bl.getList().get(0).getMain().getHumidity() +
                    "%<br>Pressure: "+bl.getList().get(0).getMain().getPressure()
                    +"hPa</body></html>");
            lbDay1.setIcon(new ImageIcon(ImageIO.read(new URL("http://openweathermap.org/img/wn/"+bl.getList().get(0).getWeather().get(0).getIcon()+".png"))));
            lbDay2.setText("<html><body><h2>TOMORROW</h2><p style='font-size:130%;'>"
                    +String.valueOf(bl.avgTemp(bl.getNextDay())).substring(0, 3)+" °C</p>"
                    +bl.getList().get(8).getWeather().get(0).getDescription()+" <br>Min/Max: "
                    +String.valueOf(bl.avgminTemp(bl.getNextDay())).substring(0, 3)+"° / "
                    + String.valueOf(bl.avgmaxTemp(bl.getNextDay())).substring(0, 3)
                    +"°<br>Humidity: "+bl.getList().get(8).getMain().getHumidity() +
                    "%<br>Pressure: "+bl.getList().get(8).getMain().getPressure()
                    +"hPa</body></html>");
            lbDay2.setIcon(new ImageIcon(ImageIO.read(new URL("http://openweathermap.org/img/wn/"+bl.getList().get(8).getWeather().get(0).getIcon()+".png"))));
            lbDay3.setText("<html><body><h3>"
                    +bl.getList().get(16).getDt_txt().replace('-', '.').substring(0, 10)+"</h3>"
                    +String.valueOf(bl.avgminTemp(bl.getNextDay()+8)).substring(0, 3)+"° / "
                    + String.valueOf(bl.avgmaxTemp(bl.getNextDay()+8)).substring(0, 3)
                    +" °C<br>"+bl.getList().get(16).getWeather().get(0).getDescription()
                    +"</body></html>");
            lbDay3.setIcon(new ImageIcon(ImageIO.read(new URL("http://openweathermap.org/img/wn/"+bl.getList().get(16).getWeather().get(0).getIcon()+".png"))));
            lbDay4.setText("<html><body><h3>"
                    +bl.getList().get(24).getDt_txt().replace('-', '.').substring(0, 10)+"</h3>"
                    +String.valueOf(bl.avgminTemp(bl.getNextDay()+16)).substring(0, 3)
                    +"° / "+ String.valueOf(bl.avgmaxTemp(bl.getNextDay()+16)).substring(0, 3)
                    +" °C<br>"+bl.getList().get(24).getWeather().get(0).getDescription()
                    +"</body></html>");
            lbDay4.setIcon(new ImageIcon(ImageIO.read(new URL("http://openweathermap.org/img/wn/"+bl.getList().get(24).getWeather().get(0).getIcon()+".png"))));
            lbDay5.setText("<html><body><h3>"
                    +bl.getList().get(32).getDt_txt().replace('-', '.').substring(0, 10)
                    +"</h3>"+String.valueOf(bl.avgminTemp(bl.getNextDay()+24)).substring(0, 3)
                    +"° / "+ String.valueOf(bl.avgmaxTemp(bl.getNextDay()+24)).substring(0, 3)
                    +" °C<br>"+bl.getList().get(32).getWeather().get(0).getDescription()
                    +"</body></html>");
            lbDay5.setIcon(new ImageIcon(ImageIO.read(new URL("http://openweathermap.org/img/wn/"+bl.getList().get(32).getWeather().get(0).getIcon()+".png"))));       
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbLocationActionPerformed

    private void miCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompActionPerformed
        CompareToolDialog ctd = new CompareToolDialog(this, true, this);
        ctd.setVisible(true); 
    }//GEN-LAST:event_miCompActionPerformed

    private void lbDay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDay1MouseClicked
         selectDay = 1;
         //openselectedDayDetail();
    }//GEN-LAST:event_lbDay1MouseClicked

    private void lbDay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDay2MouseClicked
        selectDay = 2;
        //openselectedDayDetail();
    }//GEN-LAST:event_lbDay2MouseClicked

    private void lbDay3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDay3MouseClicked
        selectDay = 3;
        //openselectedDayDetail();
    }//GEN-LAST:event_lbDay3MouseClicked

    private void lbDay4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDay4MouseClicked
        selectDay = 4;
        openselectedDayDetail();
    }//GEN-LAST:event_lbDay4MouseClicked

    private void lbDay5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDay5MouseClicked
        selectDay = 5;
        //openselectedDayDetail();
    }//GEN-LAST:event_lbDay5MouseClicked

    public void openselectedDayDetail()
    {
        WeatherDetail wd = new WeatherDetail(this, true);
        wd.setVisible(true);
//        wd.lbInit(cbLocation.getSelectedIndex(), selectDay);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDay1;
    private javax.swing.JLabel lbDay2;
    private javax.swing.JLabel lbDay3;
    private javax.swing.JLabel lbDay4;
    private javax.swing.JLabel lbDay5;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miComp;
    private javax.swing.JMenuItem miRemove;
    private javax.swing.JPanel pnFirstTwoDays;
    private javax.swing.JPanel pnOtherDays;
    // End of variables declaration//GEN-END:variables

}
