/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.TravelGuideBL;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Patrick
 */
public class WeatherDetail extends javax.swing.JDialog {

    /**
     * Creates new form WeatherDetail
     */
    public TravelGuideBL tgbl = new TravelGuideBL();
    
    public WeatherDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        compAdd();
        cbInit();
    }
    
    public void compAdd()
    {
        
    }
    
    public void cbInit()
    {
//        TravelGuideBL bl = tgbl.getWeatherData(0);
        cbDiffDay1.addItem("TODAY");
        cbDiffDay1.addItem("TOMORROW");
//        cbDiffDay1.addItem(bl.getList().get(bl.getNextDay()+8).getDt_txt().replace('-', '.').substring(0, 10));
//        cbDiffDay1.addItem(bl.getList().get(bl.getNextDay()+16).getDt_txt().replace('-', '.').substring(0, 10));
//        cbDiffDay1.addItem(bl.getList().get(bl.getNextDay()+24).getDt_txt().replace('-', '.').substring(0, 10));
        
        cbDiffDay1.setSelectedIndex(0);
        cbDiffDay1.updateUI();       
    }
    
    public void lbInit(int city, int day)
    {
//        TravelGuideBL townbl = tgbl.getWeatherData(city);
//        lbDiffDay1.setText("<html><body><h3>"
//                    +townbl.getList().get(16).getDt_txt().replace('-', '.').substring(0, 10)+"</h3>"
//                    +String.valueOf(townbl.avgminTemp(townbl.getNextDay()+8)).substring(0, 3)+"° / "
//                    + String.valueOf(townbl.avgmaxTemp(townbl.getNextDay()+8)).substring(0, 3)
//                    +" °C<br>"+townbl.getList().get(16).getWeather().get(0).getDescription()
//                    +"</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        slNumberDays = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        cbDiffDay1 = new javax.swing.JComboBox<>();
        cbDiffDay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pbHum1 = new javax.swing.JProgressBar();
        pbHum2 = new javax.swing.JProgressBar();
        btClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mOption = new javax.swing.JMenu();
        cbmiOption = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel7.setLayout(new java.awt.GridLayout());

        slNumberDays.setMaximum(5);
        slNumberDays.setMinimum(1);
        jPanel7.add(slNumberDays);

        jPanel1.add(jPanel7);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel6.setLayout(new java.awt.GridLayout());

        jPanel6.add(cbDiffDay1);

        jPanel6.add(cbDiffDay);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel4.setMinimumSize(new java.awt.Dimension(59, 45));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        pbHum1.setBackground(new java.awt.Color(0, 0, 0));
        pbHum1.setForeground(new java.awt.Color(102, 102, 102));
        pbHum1.setValue(50);
        pbHum1.setBorder(javax.swing.BorderFactory.createTitledBorder("Humidity"));
        pbHum1.setStringPainted(true);
        jPanel5.add(pbHum1);

        pbHum2.setValue(50);
        pbHum2.setBorder(javax.swing.BorderFactory.createTitledBorder("Humidity"));
        pbHum2.setOpaque(true);
        pbHum2.setStringPainted(true);
        jPanel5.add(pbHum2);

        jPanel4.add(jPanel5);

        btClose.setText("Close");
        btClose.setMaximumSize(new java.awt.Dimension(59, 15));
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });
        jPanel4.add(btClose);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout());
        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        mOption.setText("Option");

        cbmiOption.setSelected(true);
        cbmiOption.setText("Compare?");
        cbmiOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmiOptionActionPerformed(evt);
            }
        });
        mOption.add(cbmiOption);

        jMenuBar1.add(mOption);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void cbmiOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmiOptionActionPerformed
        if(cbmiOption.isSelected())
        {
            slNumberDays.setVisible(true);
            compToolEnable();
        }
        else
        {
            slNumberDays.setVisible(false);
        }
    }//GEN-LAST:event_cbmiOptionActionPerformed
    
    public void compToolEnable()
    {
        jPanel3.setLayout(new GridLayout(1, slNumberDays.getValue()));
        jPanel5.setLayout(new GridLayout(1, slNumberDays.getValue()));
        jPanel6.setLayout(new GridLayout(1, slNumberDays.getValue()));
        JLabel lbDay1 = new JLabel();
        lbDay1.setBackground(Color.red);
        jPanel3.add(lbDay1);
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JComboBox<String> cbDiffDay;
    private javax.swing.JComboBox<String> cbDiffDay1;
    private javax.swing.JCheckBoxMenuItem cbmiOption;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JMenu mOption;
    private javax.swing.JProgressBar pbHum1;
    private javax.swing.JProgressBar pbHum2;
    private javax.swing.JSlider slNumberDays;
    // End of variables declaration//GEN-END:variables
}
